### ISSUE TITLE
The code of fnf on adult dataset

### ISSUE THREAD

**Issue by zaocan666** [eth-sri/fnf#1]
It looks like train_enc_categorical.py and train_gen_categorical do not involve the normalizing flow method.
Is the fnf implemented on the categorical datasets?

**Comment by mbalunovic** [comment]
Hi, for categorical datasets we use a different procedure for learning the bijection (not involving the normalizing flow).
See the paragraph "Bijective encoders for categorical data" in our paper.

**Comment by mbalunovic** [comment]
Hi, for categorical datasets we use a different procedure for learning the bijection (not involving the normalizing flow).
See the paragraph "Bijective encoders for categorical data" in our paper.

**Comment by zaocan666** [comment]
ok, thank you for replying
